// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfnuokwfcxrsvbfpbqiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmbnVva3dmY3hyc3ZiZnBicWl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyOTcyMDksImV4cCI6MjA2Njg3MzIwOX0.JAJql4bh4LD8anUPA9zthQOi_wWxpqApinVa6oRNCQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});